# -*- coding: utf-8 -*-
"""plotter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G1bPUdP9PFu9zYCQrGabtR7AL_sR4Hml
"""
import matplotlib.pyplot as plt

def plotter_3d(D_train=X_train,D_test=X_test,
            y_train=y_train,y_test=y_test,
            predictions=None):
  ax = plt.figure().add_subplot(projection='3d')
  ax.scatter(D_train[:,0],D_train[:,1],y_train.squeeze(),c='b')
  ax.scatter(D_test[:,0],D_test[:,1],y_test.squeeze(),c='g')
  if predictions is not None:
    ax.scatter(D_test[:,0],D_test[:,1],predictions.squeeze(),c='p')
  plt.show()

def plotter(D_train=X_train,D_test=X_test,
            y_train=y_train,y_test=y_test,
            predictions=None):
  plt.scatter(D_train,y_train.squeeze(),c='b')
  plt.scatter(D_test,y_test.squeeze(),c='g')
  if predictions is not None:
    plt.scatter(D_test,predictions.squeeze(),c='p')
  plt.show()
